"""add AuditMixin fields to User and OAuthAccount

Revision ID: 3a8e01c1880d
Revises: 1ad61170e391
Create Date: 2026-02-15 13:42:16.218824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8e01c1880d'
down_revision: Union[str, Sequence[str], None] = '1ad61170e391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_account', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('oauth_account', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('oauth_account', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_oauth_account_deleted_at'), 'oauth_account', ['deleted_at'], unique=False)
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_index(op.f('ix_oauth_account_deleted_at'), table_name='oauth_account')
    op.drop_column('oauth_account', 'deleted_at')
    op.drop_column('oauth_account', 'updated_at')
    op.drop_column('oauth_account', 'created_at')
    # ### end Alembic commands ###
