"""user_action_logs

Revision ID: d543e6a6d98c
Revises: cb17001d6de5
Create Date: 2026-04-19 16:24:08.993876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd543e6a6d98c'
down_revision: Union[str, Sequence[str], None] = 'cb17001d6de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_action_logs_event_type'), 'user_action_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_action_logs_user_id'), 'user_action_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_action_logs_user_id'), table_name='user_action_logs')
    op.drop_index(op.f('ix_user_action_logs_event_type'), table_name='user_action_logs')
    op.drop_table('user_action_logs')
    # ### end Alembic commands ###
